/*
 * CLASH ARENA HD - Arquivo Principal
 */
const ALL_CARDS = {
    knight: { name: 'Cavaleiro', icon: '🗡️', cost: 3, hp: 800, damage: 90, speed: 1.2, range: 30, attackSpeed: 1100, rarity: 'common', color: '#f39c12' },
    archer: { name: 'Arqueira', icon: '🏹', cost: 3, hp: 300, damage: 60, speed: 1.0, range: 120, attackSpeed: 900, rarity: 'common', color: '#e91e63', count: 2 },
    skeleton: { name: 'Esqueletos', icon: '💀', cost: 1, hp: 60, damage: 40, speed: 1.8, range: 25, attackSpeed: 500, rarity: 'common', color: '#bdc3c7', count: 3 },
    goblin: { name: 'Goblins', icon: '👺', cost: 2, hp: 150, damage: 50, speed: 1.5, range: 25, attackSpeed: 600, rarity: 'common', color: '#27ae60', count: 3 },
    minion: { name: 'Lacaios', icon: '👿', cost: 3, hp: 180, damage: 50, speed: 1.5, range: 50, attackSpeed: 700, rarity: 'common', color: '#3f51b5', flying: true, count: 3 },
    fireball: { name: 'Bola de Fogo', icon: '🔥', cost: 4, damage: 400, radius: 80, type: 'spell', rarity: 'common', color: '#ff5722' },
    giant: { name: 'Gigante', icon: '👹', cost: 5, hp: 2500, damage: 150, speed: 0.6, range: 30, attackSpeed: 1500, rarity: 'rare', color: '#795548', targetBuildings: true },
    musketeer: { name: 'Mosqueteira', icon: '🔫', cost: 4, hp: 500, damage: 120, speed: 1.0, range: 140, attackSpeed: 1000, rarity: 'rare', color: '#9c27b0' },
    valkyrie: { name: 'Valquíria', icon: '⚔️', cost: 4, hp: 1000, damage: 100, speed: 1.0, range: 35, attackSpeed: 1300, rarity: 'rare', color: '#e91e63', splash: true, splashRadius: 55 },
    bomber: { name: 'Bombardeiro', icon: '💣', cost: 3, hp: 250, damage: 180, speed: 0.9, range: 100, attackSpeed: 1200, rarity: 'rare', color: '#607d8b', splash: true, splashRadius: 40 },
    witch: { name: 'Bruxa', icon: '🧙‍♀️', cost: 5, hp: 600, damage: 80, speed: 0.9, range: 110, attackSpeed: 1000, rarity: 'epic', color: '#8e44ad' },
    prince: { name: 'Príncipe', icon: '🤴', cost: 5, hp: 1200, damage: 200, speed: 1.4, range: 30, attackSpeed: 1400, rarity: 'epic', color: '#3498db' },
    wizard: { name: 'Mago', icon: '🧙', cost: 5, hp: 450, damage: 150, speed: 0.9, range: 130, attackSpeed: 1100, rarity: 'epic', color: '#9b59b6', splash: true, splashRadius: 50 },
    hog_rider: { name: 'Corredor', icon: '🐗', cost: 4, hp: 800, damage: 180, speed: 2.0, range: 30, attackSpeed: 1000, rarity: 'epic', color: '#e67e22', targetBuildings: true },
    baby_dragon: { name: 'Dragão Bebê', icon: '🐲', cost: 4, hp: 800, damage: 100, speed: 1.2, range: 80, attackSpeed: 1200, rarity: 'epic', color: '#1abc9c', flying: true, splash: true, splashRadius: 35 },
    mini_pekka: { name: 'Mini PEKKA', icon: '🤖', cost: 4, hp: 700, damage: 350, speed: 1.3, range: 30, attackSpeed: 1500, rarity: 'epic', color: '#2c3e50' },
    golem: { name: 'Golem', icon: '🗿', cost: 8, hp: 4000, damage: 200, speed: 0.4, range: 30, attackSpeed: 2000, rarity: 'legendary', color: '#7f8c8d', targetBuildings: true },
    pekka: { name: 'PEKKA', icon: '🦾', cost: 7, hp: 3000, damage: 500, speed: 0.6, range: 30, attackSpeed: 1800, rarity: 'legendary', color: '#1a237e' },
    electro_wizard: { name: 'Mago Elétrico', icon: '⚡', cost: 4, hp: 500, damage: 100, speed: 1.0, range: 120, attackSpeed: 900, rarity: 'legendary', color: '#00bcd4' },
    mega_knight: { name: 'Mega Cavaleiro', icon: '🦸', cost: 7, hp: 3200, damage: 250, speed: 0.8, range: 35, attackSpeed: 1600, rarity: 'legendary', color: '#1a237e', splash: true, splashRadius: 60 },
    sparky: { name: 'Sparky', icon: '🔋', cost: 6, hp: 1200, damage: 1000, speed: 0.5, range: 80, attackSpeed: 4000, rarity: 'legendary', color: '#ffc107' },
    royal_giant: { name: 'Gigante Real', icon: '👑', cost: 6, hp: 2200, damage: 180, speed: 0.7, range: 150, attackSpeed: 1500, rarity: 'legendary', color: '#3f51b5', targetBuildings: true },
    lava_hound: { name: 'Cão de Lava', icon: '🌋', cost: 7, hp: 3500, damage: 50, speed: 0.6, range: 40, attackSpeed: 1300, rarity: 'legendary', color: '#e74c3c', flying: true, targetBuildings: true },
    arrows: { name: 'Flechas', icon: '➵', cost: 3, damage: 200, radius: 100, type: 'spell', rarity: 'common', color: '#795548' },
    zap: { name: 'Zap', icon: '⚡', cost: 2, damage: 150, radius: 70, type: 'spell', rarity: 'common', color: '#f1c40f' },
    barbarian: { name: 'Bárbaros', icon: '🪓', cost: 5, hp: 400, damage: 80, speed: 1.0, range: 25, attackSpeed: 1000, rarity: 'common', color: '#f39c12', count: 4 }
};

const STAGES = [
    { id: 1, name: 'Vila dos Goblins', bg1: '#2d5a35', bg2: '#1a3d20', enemyLevel: 1, reward: [], gold: 50, time: 180 },
    { id: 2, name: 'Floresta Sombria', bg1: '#1a3d20', bg2: '#0d1f10', enemyLevel: 2, reward: ['giant', 'musketeer'], gold: 80, time: 180 },
    { id: 3, name: 'Montanhas Geladas', bg1: '#4a6fa5', bg2: '#2a4a75', enemyLevel: 3, reward: ['valkyrie', 'bomber'], gold: 120, time: 170 },
    { id: 4, name: 'Pântano Maldito', bg1: '#3d5a3d', bg2: '#1d3a1d', enemyLevel: 4, reward: ['witch', 'prince'], gold: 160, time: 170 },
    { id: 5, name: 'Deserto Ardente', bg1: '#c4a35a', bg2: '#8b7355', enemyLevel: 5, reward: ['wizard', 'hog_rider'], gold: 200, time: 160 },
    { id: 6, name: 'Caverna do Dragão', bg1: '#5a3a3a', bg2: '#3a1a1a', enemyLevel: 6, reward: ['baby_dragon', 'mini_pekka'], gold: 250, time: 160 },
    { id: 7, name: 'Fortaleza de Pedra', bg1: '#6a6a7a', bg2: '#4a4a5a', enemyLevel: 7, reward: ['golem', 'pekka'], gold: 300, time: 150 },
    { id: 8, name: 'Torre Elétrica', bg1: '#3a5a6a', bg2: '#1a3a4a', enemyLevel: 8, reward: ['electro_wizard'], gold: 400, time: 150 },
    { id: 9, name: 'Castelo das Sombras', bg1: '#3a3a4a', bg2: '#1a1a2a', enemyLevel: 9, reward: ['mega_knight', 'sparky'], gold: 500, time: 140 },
    { id: 10, name: 'Arena Lendária', bg1: '#2a1a3a', bg2: '#1a0a2a', enemyLevel: 10, reward: ['royal_giant', 'lava_hound'], gold: 1000, time: 140 }
];

const CONFIG = { MAX_ELIXIR: 10, ELIXIR_RATE: 0.008, DOUBLE_ELIXIR_TIME: 60, TOWER_RANGE: 140, TOWER_DAMAGE: 120, TOWER_ATTACK_SPEED: 600, KING_HP: 4000, PRINCESS_HP: 2500 };
const EMOTES = ['😀', '😂', '😎', '😡', '👍', '🔥'];

class ClashArena {
    constructor() {
        this.canvas = document.getElementById('arena');
        this.ctx = this.canvas.getContext('2d');
        this.particles = []; this.damageNumbers = []; this.screenShake = 0;
        this.glows = []; this.sparks = []; this.grass = [];
        this.loadProgress(); this.setupDOM(); this.reset(); this.init();
    }
    
    loadProgress() {
        const s = localStorage.getItem('clashUltimate');
        if (s) { const d = JSON.parse(s); this.stage = d.stage||1; this.unlocked = d.unlocked||['knight','archer','skeleton','goblin','minion','fireball','arrows','zap']; this.deck = d.deck||['knight','archer','skeleton','goblin','minion','fireball','arrows','zap']; this.gold = d.gold||100; this.cardLevels = d.cardLevels||{}; this.totalWins = d.totalWins||0; }
        else { this.stage = 1; this.unlocked = ['knight','archer','skeleton','goblin','minion','fireball','arrows','zap']; this.deck = [...this.unlocked]; this.gold = 100; this.cardLevels = {}; this.totalWins = 0; }
    }
    
    save() { localStorage.setItem('clashUltimate', JSON.stringify({ stage: this.stage, unlocked: this.unlocked, deck: this.deck, gold: this.gold, cardLevels: this.cardLevels, totalWins: this.totalWins })); }
    getCardLevel(id) { return this.cardLevels[id] || 1; }
    getUpgradeCost(id) { const l = this.getCardLevel(id); const c = ALL_CARDS[id]; return (c.rarity === 'legendary' ? 500 : c.rarity === 'epic' ? 200 : c.rarity === 'rare' ? 100 : 50) * l; }
    upgradeCard(id) { const cost = this.getUpgradeCost(id); if (this.gold >= cost && this.getCardLevel(id) < 10) { this.gold -= cost; this.cardLevels[id] = this.getCardLevel(id) + 1; this.save(); return true; } return false; }
    
    setupDOM() { this.menuScreen = document.getElementById('menu-screen'); this.gameScreen = document.getElementById('game-screen'); this.endScreen = document.getElementById('end-screen'); this.timerEl = document.getElementById('timer'); this.elixirFill = document.getElementById('elixir-fill'); this.elixirCount = document.getElementById('elixir-count'); this.handCards = document.getElementById('hand-cards'); this.nextCardSlot = document.getElementById('next-card'); this.resultText = document.getElementById('result-text'); this.playerCrowns = document.getElementById('player-crowns'); this.enemyCrowns = document.getElementById('enemy-crowns'); }
    
    reset() { this.running = false; this.elixir = 5; this.enemyElixir = 2; this.time = 180; this.selected = null; this.hand = []; this.next = null; this.troops = []; this.projectiles = []; this.effects = []; this.particles = []; this.damageNumbers = []; this.screenShake = 0; this.doubleElixir = false; this.stats = { spawned: 0, damage: 0 }; this.glows = []; this.sparks = [];
        this.towers = { player: { king: { hp: CONFIG.KING_HP * 1.5, max: CONFIG.KING_HP * 1.5, active: false, last: 0 }, left: { hp: CONFIG.PRINCESS_HP * 1.5, max: CONFIG.PRINCESS_HP * 1.5, active: true, last: 0 }, right: { hp: CONFIG.PRINCESS_HP * 1.5, max: CONFIG.PRINCESS_HP * 1.5, active: true, last: 0 } }, enemy: { king: { hp: CONFIG.KING_HP, max: CONFIG.KING_HP, active: false, last: 0 }, left: { hp: CONFIG.PRINCESS_HP, max: CONFIG.PRINCESS_HP, active: true, last: 0 }, right: { hp: CONFIG.PRINCESS_HP, max: CONFIG.PRINCESS_HP, active: true, last: 0 } } }; }
    
    genGrass() { this.grass = []; for (let i = 0; i < 50; i++) this.grass.push({ x: Math.random() * this.canvas.width, y: Math.random() * this.canvas.height, s: 4 + Math.random() * 5 }); }
    
    init() { this.resize(); window.onresize = () => this.resize(); this.canvas.onclick = (e) => this.canvasClick(e); this.canvas.ontouchend = (e) => { e.preventDefault(); if (e.changedTouches.length > 0) { const touch = e.changedTouches[0]; this.canvasClick({ clientX: touch.clientX, clientY: touch.clientY }); } }; this.handCards.onclick = (e) => { const c = e.target.closest('.card'); if (c && !c.classList.contains('disabled')) this.selectCard(parseInt(c.dataset.index)); }; document.getElementById('start-btn').onclick = () => this.showStages(); document.getElementById('restart-btn').onclick = () => this.showStages(); this.updateMenu(); }
    
    updateMenu() { let info = document.querySelector('.stage-info'); if (!info) { info = document.createElement('div'); info.className = 'stage-info'; const tag = document.querySelector('.tagline'); if (tag) tag.after(info); } info.innerHTML = `<div class="gold-display">💰 ${this.gold} ouro</div><div>Fase ${this.stage}: ${STAGES[this.stage-1].name}</div><div>🃏 ${this.unlocked.length} cartas | 🏆 ${this.totalWins} vitórias</div>`; }
    
    showStages() { let m = document.getElementById('stage-modal') || document.createElement('div'); m.id = 'stage-modal'; m.className = 'modal'; let html = ''; STAGES.forEach((s, i) => { const ok = i + 1 <= this.stage; html += `<div class="stage-item ${ok ? 'unlocked' : 'locked'}" data-stage="${i+1}"><span>${i+1}. ${s.name}</span><span>${ok ? `💰${s.gold}` : '🔒'}</span></div>`; }); m.innerHTML = `<div class="modal-content"><h2>🗺️ FASES</h2><div class="gold-header">💰 ${this.gold} ouro</div><div class="stages-grid">${html}</div><div class="modal-buttons"><button class="deck-modal-btn">🃏 DECK</button><button class="upgrade-modal-btn">⬆️ UPGRADES</button><button class="close-modal">✕</button></div></div>`; document.body.appendChild(m); m.style.display = 'flex'; m.querySelectorAll('.stage-item.unlocked').forEach(el => el.onclick = () => { m.style.display = 'none'; this.start(parseInt(el.dataset.stage)); }); m.querySelector('.deck-modal-btn').onclick = () => { m.style.display = 'none'; this.showDeckEditor(); }; m.querySelector('.upgrade-modal-btn').onclick = () => { m.style.display = 'none'; this.showUpgrades(); }; m.querySelector('.close-modal').onclick = () => m.style.display = 'none'; }
    
    showUpgrades() { let m = document.getElementById('upgrade-modal') || document.createElement('div'); m.id = 'upgrade-modal'; m.className = 'modal'; const render = () => { let html = ''; this.unlocked.forEach(id => { const c = ALL_CARDS[id]; if (!c) return; const lvl = this.getCardLevel(id); const cost = this.getUpgradeCost(id); const can = this.gold >= cost && lvl < 10; html += `<div class="upgrade-card ${c.rarity}" data-card="${id}"><span class="up-icon">${c.icon}</span><span class="up-name">${c.name} Lv.${lvl}</span><button class="up-btn ${can ? '' : 'disabled'}">${lvl >= 10 ? 'MAX' : `⬆️${cost}💰`}</button></div>`; }); m.innerHTML = `<div class="modal-content"><h2>⬆️ UPGRADES</h2><div class="gold-header">💰 ${this.gold} ouro</div><div class="upgrade-grid">${html}</div><button class="close-modal">✕ VOLTAR</button></div>`; m.querySelectorAll('.up-btn:not(.disabled)').forEach(btn => { btn.onclick = () => { const cid = btn.closest('.upgrade-card').dataset.card; if (this.upgradeCard(cid)) { this.showToast(`${ALL_CARDS[cid].name} melhorado!`); render(); } }; }); m.querySelector('.close-modal').onclick = () => { m.style.display = 'none'; this.showStages(); }; }; document.body.appendChild(m); m.style.display = 'flex'; render(); }
    
    showToast(msg) { const t = document.createElement('div'); t.className = 'game-toast'; t.textContent = msg; document.body.appendChild(t); setTimeout(() => t.remove(), 2000); }
    
    showDeckEditor() { let m = document.getElementById('deck-modal') || document.createElement('div'); m.id = 'deck-modal'; m.className = 'modal'; const render = () => { let dh = '', ah = ''; for (let i = 0; i < 8; i++) { const cid = this.deck[i]; if (cid && ALL_CARDS[cid]) { const c = ALL_CARDS[cid]; dh += `<div class="deck-card ${c.rarity}" data-card="${cid}"><span>${c.icon}</span><small>${c.name}</small><button class="rm">✕</button></div>`; } else dh += `<div class="deck-card empty">+</div>`; } this.unlocked.filter(id => !this.deck.includes(id)).forEach(id => { const c = ALL_CARDS[id]; if (c) ah += `<div class="avail-card ${c.rarity}" data-card="${id}"><span>${c.icon}</span><small>${c.name}</small></div>`; }); m.innerHTML = `<div class="modal-content deck-editor"><h2>🃏 DECK (${this.deck.length}/8)</h2><div class="deck-grid">${dh}</div><h3>Disponíveis</h3><div class="avail-grid">${ah||'<p>Nenhuma</p>'}</div><button class="close-modal">✓ SALVAR</button></div>`; m.querySelectorAll('.rm').forEach(b => b.onclick = (e) => { e.stopPropagation(); this.deck = this.deck.filter(x => x !== b.parentElement.dataset.card); this.save(); render(); }); m.querySelectorAll('.avail-card').forEach(el => el.onclick = () => { if (this.deck.length < 8) { this.deck.push(el.dataset.card); this.save(); render(); } }); m.querySelector('.close-modal').onclick = () => { m.style.display = 'none'; this.showStages(); }; }; document.body.appendChild(m); m.style.display = 'flex'; render(); }
    
    resize() { const p = this.canvas.parentElement; const isMobile = window.innerWidth <= 600; const bottomHudHeight = isMobile ? 140 : 180; this.canvas.width = p.clientWidth || 400; this.canvas.height = Math.max(300, (p.clientHeight || 600) - bottomHudHeight); const w = this.canvas.width, h = this.canvas.height; this.towers.player.king.x = w/2; this.towers.player.king.y = h - 45; this.towers.player.left.x = w*0.22; this.towers.player.left.y = h - 90; this.towers.player.right.x = w*0.78; this.towers.player.right.y = h - 90; this.towers.enemy.king.x = w/2; this.towers.enemy.king.y = 45; this.towers.enemy.left.x = w*0.22; this.towers.enemy.left.y = 90; this.towers.enemy.right.x = w*0.78; this.towers.enemy.right.y = 90; this.genGrass(); }
    
    start(stageNum) { this.reset(); this.playingStage = stageNum; const s = STAGES[stageNum - 1]; this.running = true; this.elixir = 5; this.enemyElixir = 1 + stageNum * 0.2; this.time = s.time; this.enemyLevel = s.enemyLevel; this.menuScreen.classList.add('hidden'); this.endScreen.classList.add('hidden'); this.gameScreen.classList.remove('hidden'); this.createEmoteBar(); this.gameDeck = [...this.deck]; for (let i = this.gameDeck.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [this.gameDeck[i], this.gameDeck[j]] = [this.gameDeck[j], this.gameDeck[i]]; } this.hand = this.gameDeck.slice(0, 4); this.next = this.gameDeck[4]; this.renderCards(); this.genGrass(); setTimeout(() => this.resize(), 50); if (this.timer) clearInterval(this.timer); this.timer = setInterval(() => { this.time--; if (this.time === CONFIG.DOUBLE_ELIXIR_TIME && !this.doubleElixir) { this.doubleElixir = true; this.showToast('⚡ DOUBLE ELIXIR! ⚡'); this.screenShake = 20; } this.timerEl.textContent = `${Math.floor(this.time/60)}:${(this.time%60).toString().padStart(2,'0')}`; this.timerEl.className = this.doubleElixir ? 'double-elixir' : ''; if (this.time <= 0) this.end(); }, 1000); this.lastTime = performance.now(); requestAnimationFrame(this.loop.bind(this)); }
    
    createEmoteBar() { let bar = document.getElementById('emote-bar'); if (!bar) { bar = document.createElement('div'); bar.id = 'emote-bar'; bar.innerHTML = EMOTES.map(e => `<span class="emote-btn">${e}</span>`).join(''); this.gameScreen.appendChild(bar); } bar.querySelectorAll('.emote-btn').forEach(btn => { btn.onclick = () => this.showEmote(btn.textContent, 'player'); }); }
    showEmote(emote, owner) { const e = document.createElement('div'); e.className = `emote-bubble ${owner}`; e.textContent = emote; e.style.left = owner === 'player' ? '20%' : '80%'; e.style.top = owner === 'player' ? '70%' : '30%'; this.gameScreen.appendChild(e); setTimeout(() => e.remove(), 2000); }
    
    selectCard(i) { if (i < 0 || i >= this.hand.length) return; const c = ALL_CARDS[this.hand[i]]; if (!c || Math.floor(this.elixir) < c.cost) return; this.selected = this.selected === i ? null : i; this.renderCards(); }
    
    renderCards() { this.handCards.innerHTML = ''; this.hand.forEach((id, i) => { const c = ALL_CARDS[id]; if (!c) return; const ok = Math.floor(this.elixir) >= c.cost; const lvl = this.getCardLevel(id); const div = document.createElement('div'); div.className = `card ${c.rarity || ''} ${ok ? '' : 'disabled'} ${this.selected === i ? 'selected' : ''}`; div.dataset.index = i; div.innerHTML = `<div class="card-cost">${c.cost}</div><div class="card-icon">${c.icon}</div><div class="card-name">${c.name}</div>${lvl > 1 ? `<div class="card-level">Lv${lvl}</div>` : ''}`; this.handCards.appendChild(div); }); if (this.next && ALL_CARDS[this.next]) this.nextCardSlot.innerHTML = `<div class="card-icon" style="font-size:1.5rem">${ALL_CARDS[this.next].icon}</div><div class="next-card-label">PRÓX</div>`; }
    
    canvasClick(e) { if (this.selected === null) return; const r = this.canvas.getBoundingClientRect(); const x = (e.clientX - r.left) * (this.canvas.width / r.width); const y = (e.clientY - r.top) * (this.canvas.height / r.height); if (y < this.canvas.height * 0.55) { this.selected = null; this.renderCards(); return; } const id = this.hand[this.selected], c = ALL_CARDS[id]; if (!c || Math.floor(this.elixir) < c.cost) return; this.elixir -= c.cost; if (c.type === 'spell') this.spell(id, x, y); else this.spawn(id, x, y, 'player'); this.hand.splice(this.selected, 1); if (this.next) { this.hand.push(this.next); const av = this.gameDeck.filter(c => !this.hand.includes(c)); this.next = av.length ? av[Math.floor(Math.random() * av.length)] : null; } this.selected = null; this.renderCards(); }
    
    spawn(id, x, y, owner) { const c = ALL_CARDS[id], n = c.count || 1; const lvlBonus = owner === 'player' ? 1 + (this.getCardLevel(id) - 1) * 0.1 : 1; const enemyMult = owner === 'enemy' ? 0.6 + (this.enemyLevel - 1) * 0.06 : 1; const mult = lvlBonus * enemyMult; for (let i = 0; i < n; i++) { const tx = x + (i - (n-1)/2) * 25, ty = y + Math.floor(i/2) * 20; this.troops.push({ id: Date.now() + Math.random(), cardId: id, owner, x: tx, y: ty, hp: c.hp * mult, max: c.hp * mult, dmg: c.damage * mult, spd: c.speed, rng: c.range, atkSpd: c.attackSpeed, last: 0, fly: c.flying, tgtBld: c.targetBuildings, splash: c.splash, splashR: c.splashRadius || 0, color: c.color, icon: c.icon, size: c.hp > 1000 ? 28 : c.hp > 300 ? 22 : 18, rarity: c.rarity }); this.spawnParticles(tx, ty, owner === 'player' ? '#3498db' : '#e74c3c', 20); this.glows.push({ x: tx, y: ty, color: owner === 'player' ? '#3498db' : '#e74c3c', size: 50, life: 1 }); this.effects.push({ type: 'spawn', x: tx, y: ty, t: 0, dur: 500, color: owner === 'player' ? '#3498db' : '#e74c3c' }); } if (owner === 'player') this.stats.spawned += n; }
    
    spawnParticles(x, y, color, count) { for (let i = 0; i < count; i++) this.particles.push({ x, y, vx: (Math.random() - 0.5) * 10, vy: (Math.random() - 0.5) * 10 - 3, life: 1, decay: 0.02, size: 4 + Math.random() * 5, color }); }
    addDamageNumber(x, y, damage, isPlayer) { this.damageNumbers.push({ x: x + (Math.random()-0.5)*20, y, damage: Math.round(damage), life: 1, vy: -2.5, color: isPlayer ? '#3498db' : '#e74c3c' }); }
    
    spell(id, x, y) { const c = ALL_CARDS[id]; const lvlBonus = 1 + (this.getCardLevel(id) - 1) * 0.1; const damage = c.damage * lvlBonus; this.effects.push({ type: 'explosion', x, y, t: 0, dur: 800, r: c.radius, color: c.color }); this.spawnParticles(x, y, c.color, 40); this.glows.push({ x, y, color: c.color, size: c.radius * 1.5, life: 1 }); this.screenShake = 15; for (let i = 0; i < 20; i++) this.sparks.push({ x: x + (Math.random()-0.5)*c.radius, y: y + (Math.random()-0.5)*c.radius, vx: (Math.random()-0.5)*15, vy: (Math.random()-0.5)*15 - 5, color: ['#ff6600','#ff9900','#ffcc00'][Math.floor(Math.random()*3)], life: 1, size: 3 + Math.random()*4 }); this.troops.forEach(t => { if (Math.hypot(t.x - x, t.y - y) <= c.radius) { t.hp -= damage; this.addDamageNumber(t.x, t.y, damage, true); this.stats.damage += damage; } }); Object.values(this.towers).forEach(side => Object.values(side).forEach(tw => { if (tw.hp > 0 && Math.hypot(tw.x - x, tw.y - y) <= c.radius) { tw.hp -= damage; this.addDamageNumber(tw.x, tw.y, damage, true); this.stats.damage += damage; } })); }
    
    loop(ts) { if (!this.running) return; this.update(ts - this.lastTime); this.lastTime = ts; this.render(); requestAnimationFrame(this.loop.bind(this)); }
    
    update(dt) { const elixirMult = this.doubleElixir ? 2 : 1; const rate = CONFIG.ELIXIR_RATE * elixirMult; this.elixir = Math.min(CONFIG.MAX_ELIXIR, this.elixir + rate); this.enemyElixir = Math.min(CONFIG.MAX_ELIXIR, this.enemyElixir + rate * 0.5); this.elixirFill.style.width = (this.elixir / CONFIG.MAX_ELIXIR * 100) + '%'; this.elixirFill.className = this.doubleElixir ? 'double-elixir' : ''; this.elixirCount.textContent = Math.floor(this.elixir); this.ai(); this.updateTroops(); this.updateProjectiles(); this.towerAttack(); this.particles = this.particles.filter(p => { p.x += p.vx; p.y += p.vy; p.vy += 0.15; p.life -= p.decay; return p.life > 0; }); this.damageNumbers = this.damageNumbers.filter(d => { d.y += d.vy; d.life -= 0.025; return d.life > 0; }); this.glows = this.glows.filter(g => { g.life -= 0.04; return g.life > 0; }); this.sparks = this.sparks.filter(s => { s.x += s.vx; s.y += s.vy; s.vy += 0.3; s.life -= 0.04; return s.life > 0; }); if (this.screenShake > 0) this.screenShake *= 0.9; this.effects = this.effects.filter(e => { e.t += 16; return e.t < e.dur; }); this.checkWin(); this.renderCards(); }
    
    updateTroops() { const now = Date.now(), w = this.canvas.width, h = this.canvas.height; const rT = h * 0.46, rB = h * 0.54; const br = [{ l: w * 0.12, r: w * 0.35, c: w * 0.235 }, { l: w * 0.65, r: w * 0.88, c: w * 0.765 }]; this.troops = this.troops.filter(t => { if (t.hp <= 0) { this.spawnParticles(t.x, t.y, t.color, 25); this.glows.push({ x: t.x, y: t.y, color: t.color, size: 40, life: 1 }); for(let i=0;i<8;i++) this.sparks.push({x:t.x,y:t.y,vx:(Math.random()-0.5)*12,vy:(Math.random()-0.5)*12-4,color:t.color,life:1,size:3}); return false; } return true; }); this.troops.forEach(t => { const tgt = this.findTarget(t); if (!tgt) return; const d = Math.hypot(tgt.x - t.x, tgt.y - t.y); if (d <= t.rng) { if (now - t.last >= t.atkSpd) { this.attack(t, tgt); t.last = now; } } else { const a = Math.atan2(tgt.y - t.y, tgt.x - t.x); let nx = t.x + Math.cos(a) * t.spd, ny = t.y + Math.sin(a) * t.spd; if (!t.fly && ny > rT && ny < rB) { const onBr = br.some(b => nx >= b.l && nx <= b.r); if (!onBr) { const cl = br.reduce((a, b) => Math.abs(t.x - a.c) < Math.abs(t.x - b.c) ? a : b); nx = t.x + (cl.c > t.x ? 1 : -1) * t.spd; ny = t.y; } } t.x = Math.max(15, Math.min(w - 15, nx)); t.y = Math.max(15, Math.min(h - 15, ny)); } }); }
    
    findTarget(t) { const es = t.owner === 'player' ? 'enemy' : 'player'; let cl = null, cd = Infinity; if (t.tgtBld) { Object.values(this.towers[es]).forEach(tw => { if (tw.hp > 0 && (tw.active || tw.max >= CONFIG.KING_HP)) { const d = Math.hypot(tw.x - t.x, tw.y - t.y); if (d < cd) { cd = d; cl = tw; } } }); return cl; } this.troops.forEach(e => { if (e.owner !== t.owner && e.hp > 0) { if (e.fly && t.rng < 50) return; const d = Math.hypot(e.x - t.x, e.y - t.y); if (d < cd) { cd = d; cl = e; } } }); if (!cl) Object.values(this.towers[es]).forEach(tw => { if (tw.hp > 0 && (tw.active || tw.max >= CONFIG.KING_HP)) { const d = Math.hypot(tw.x - t.x, tw.y - t.y); if (d < cd) { cd = d; cl = tw; } } }); return cl; }
    
    attack(a, tgt) { const isPlayer = a.owner === 'player'; if (a.splash) { this.troops.forEach(t => { if (t.owner !== a.owner && Math.hypot(t.x - tgt.x, t.y - tgt.y) <= a.splashR) { t.hp -= a.dmg; this.addDamageNumber(t.x, t.y, a.dmg, isPlayer); } }); this.effects.push({ type: 'splash', x: tgt.x, y: tgt.y, t: 0, dur: 300, r: a.splashR, color: a.color }); this.spawnParticles(tgt.x, tgt.y, a.color, 12); this.glows.push({ x: tgt.x, y: tgt.y, color: a.color, size: a.splashR, life: 1 }); } tgt.hp -= a.dmg; this.addDamageNumber(tgt.x, tgt.y, a.dmg, isPlayer); if (isPlayer) this.stats.damage += a.dmg; if (a.rng > 50) this.projectiles.push({ x: a.x, y: a.y, tx: tgt.x, ty: tgt.y, spd: 14, color: a.color, trail: [] }); else { this.effects.push({ type: 'hit', x: tgt.x, y: tgt.y, t: 0, dur: 200 }); for(let i=0;i<5;i++) this.sparks.push({x:tgt.x,y:tgt.y,vx:(Math.random()-0.5)*8,vy:(Math.random()-0.5)*8,color:'#fff',life:1,size:2}); } if (tgt.max === CONFIG.PRINCESS_HP && tgt.hp <= 0) { this.towers[a.owner === 'player' ? 'enemy' : 'player'].king.active = true; this.screenShake = 30; this.showToast(isPlayer ? '🏰 Torre destruída!' : '⚠️ Torre perdida!'); this.spawnParticles(tgt.x, tgt.y, '#ff6600', 40); } }
    
    updateProjectiles() { this.projectiles = this.projectiles.filter(p => { p.trail.push({x: p.x, y: p.y, life: 1}); if (p.trail.length > 8) p.trail.shift(); p.trail.forEach(t => t.life -= 0.15); const dx = p.tx - p.x, dy = p.ty - p.y, d = Math.hypot(dx, dy); if (d < p.spd) { this.effects.push({ type: 'hit', x: p.tx, y: p.ty, t: 0, dur: 200 }); this.spawnParticles(p.tx, p.ty, p.color, 8); for(let i=0;i<6;i++) this.sparks.push({x:p.tx,y:p.ty,vx:(Math.random()-0.5)*10,vy:(Math.random()-0.5)*10,color:p.color,life:1,size:2}); return false; } p.x += dx / d * p.spd; p.y += dy / d * p.spd; return true; }); }
    
    towerAttack() { const now = Date.now(); ['player', 'enemy'].forEach(side => { const es = side === 'player' ? 'enemy' : 'player'; Object.values(this.towers[side]).forEach(tw => { if (tw.hp <= 0 || (!tw.active && tw.max >= CONFIG.KING_HP)) return; let tgt = null, md = CONFIG.TOWER_RANGE; this.troops.forEach(t => { if (t.owner === es && t.hp > 0) { const d = Math.hypot(t.x - tw.x, t.y - tw.y); if (d < md) { md = d; tgt = t; } } }); if (tgt && now - tw.last >= CONFIG.TOWER_ATTACK_SPEED) { tgt.hp -= CONFIG.TOWER_DAMAGE; this.addDamageNumber(tgt.x, tgt.y, CONFIG.TOWER_DAMAGE, side === 'player'); tw.last = now; this.projectiles.push({ x: tw.x, y: tw.y, tx: tgt.x, ty: tgt.y, spd: 18, color: side === 'player' ? '#3498db' : '#e74c3c', trail: [] }); this.glows.push({ x: tw.x, y: tw.y, color: side === 'player' ? '#3498db' : '#e74c3c', size: 30, life: 1 }); } }); }); }
    
    ai() { if (Math.random() > 0.003 + this.enemyLevel * 0.0008) return; const cards = this.getEnemyCards().filter(id => { const c = ALL_CARDS[id]; return c && Math.floor(this.enemyElixir) >= c.cost && c.type !== 'spell'; }); if (!cards.length) return; const id = cards[Math.floor(Math.random() * cards.length)], c = ALL_CARDS[id]; const w = this.canvas.width, h = this.canvas.height; const bx = Math.random() > 0.5 ? w * 0.235 : w * 0.765; this.enemyElixir -= c.cost; this.spawn(id, bx + (Math.random() - 0.5) * 50, h * 0.15 + Math.random() * h * 0.15, 'enemy'); }
    
    getEnemyCards() { const b = ['knight', 'archer', 'skeleton', 'goblin', 'minion'], l = this.enemyLevel; if (l >= 2) b.push('giant', 'musketeer'); if (l >= 3) b.push('valkyrie', 'bomber'); if (l >= 4) b.push('witch', 'prince'); if (l >= 5) b.push('wizard', 'hog_rider'); if (l >= 6) b.push('baby_dragon', 'mini_pekka'); if (l >= 7) b.push('golem', 'pekka'); if (l >= 8) b.push('electro_wizard'); if (l >= 9) b.push('mega_knight', 'sparky'); if (l >= 10) b.push('royal_giant', 'lava_hound'); return b; }
    
    checkWin() { if (this.towers.player.king.hp <= 0 || this.towers.enemy.king.hp <= 0) this.end(); const pc = this.towers.enemy.king.hp <= 0 ? 3 : (this.towers.enemy.left.hp <= 0 ? 1 : 0) + (this.towers.enemy.right.hp <= 0 ? 1 : 0); const ec = this.towers.player.king.hp <= 0 ? 3 : (this.towers.player.left.hp <= 0 ? 1 : 0) + (this.towers.player.right.hp <= 0 ? 1 : 0); this.playerCrowns.textContent = `👑 ${pc}`; this.enemyCrowns.textContent = `👑 ${ec}`; }
    
    end() { this.running = false; clearInterval(this.timer); const pc = this.towers.enemy.king.hp <= 0 ? 3 : (this.towers.enemy.left.hp <= 0 ? 1 : 0) + (this.towers.enemy.right.hp <= 0 ? 1 : 0); const ec = this.towers.player.king.hp <= 0 ? 3 : (this.towers.player.left.hp <= 0 ? 1 : 0) + (this.towers.player.right.hp <= 0 ? 1 : 0); const win = pc > ec || this.towers.enemy.king.hp <= 0; let goldEarned = 0; if (win) { const stage = STAGES[this.playingStage - 1]; goldEarned = stage.gold + pc * 20; this.gold += goldEarned; this.totalWins++; if (this.playingStage === this.stage && this.stage < 10) { this.stage++; stage.reward.forEach(id => { if (!this.unlocked.includes(id)) this.unlocked.push(id); }); } this.save(); this.updateMenu(); } const emoteBar = document.getElementById('emote-bar'); if (emoteBar) emoteBar.remove(); this.gameScreen.classList.add('hidden'); this.endScreen.classList.remove('hidden'); document.getElementById('towers-destroyed').textContent = pc; document.getElementById('troops-spawned').textContent = this.stats.spawned; document.getElementById('total-damage').textContent = this.stats.damage.toLocaleString(); let goldInfo = document.getElementById('gold-earned'); if (!goldInfo) { goldInfo = document.createElement('div'); goldInfo.id = 'gold-earned'; goldInfo.className = 'stat-item'; document.querySelector('.stats-grid').appendChild(goldInfo); } goldInfo.innerHTML = `<span class="stat-value">${goldEarned}</span><span class="stat-label">💰 Ouro</span>`; this.resultText.textContent = win ? 'VITÓRIA!' : 'DERROTA'; this.resultText.className = win ? 'victory' : 'defeat'; document.querySelectorAll('#crowns-earned .crown').forEach((crown, i) => { setTimeout(() => crown.classList.toggle('earned', i < pc), i * 300); }); if (win && this.playingStage < this.stage) setTimeout(() => this.showUnlock(STAGES[this.playingStage - 1].reward), 1500); }
    
    showUnlock(ids) { if (!ids || !ids.length) return; let m = document.getElementById('unlock-modal') || document.createElement('div'); m.id = 'unlock-modal'; m.className = 'modal'; let html = ''; ids.forEach(id => { const c = ALL_CARDS[id]; if (c) html += `<div class="unlock-card ${c.rarity}"><span class="unlock-icon">${c.icon}</span><span>${c.name}</span></div>`; }); m.innerHTML = `<div class="modal-content"><h2>🎉 NOVAS CARTAS!</h2><div class="unlock-grid">${html}</div><button class="close-modal">INCRÍVEL!</button></div>`; document.body.appendChild(m); m.style.display = 'flex'; m.querySelector('.close-modal').onclick = () => m.style.display = 'none'; }
}

document.addEventListener('DOMContentLoaded', () => { window.game = new ClashArena(); });
